name: "Network-Config"
x-type: "hlfv1"
version: 1.0.0
description: "The network config"

client:
  # Which organization does this application instance belong to? The value must be the name of an org
  # defined under "organizations"
  organization: Org1

  # Some SDKs support pluggable KV stores, the properties under "credentialStore"
  # are implementation specific
  credentialStore:
    # [Optional]. Specific to FileKeyValueStore.js or similar implementations in other SDKs. Can be others
    # if using an alternative impl. For instance, CouchDBKeyValueStore.js would require an object
    # here for properties like url, db name, etc.
    path: "Org2User"

    # [Optional]. Specific to the CryptoSuite implementation. Software-based implementations like
    # CryptoSuite_ECDSA_AES.js in node SDK requires a key store. PKCS#11 based implementations does
    # not.
    cryptoStore:
      # Specific to the underlying KeyValueStore that backs the crypto key store.
      path: "Org2User"

    # [Optional]. Specific to Composer environment
    wallet: wallet-name

channels:
  crmchannel:
    orderers:
    - orderer.beijinca.com
    peers:
      peer0.org1.beijinca.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org1.beijinca.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer2.org1.beijinca.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    chaincodes:
    - crm:v1
    - mycc:v1

organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.beijinca.com
    - peer1.org1.beijinca.com
    - peer2.org1.beijinca.com
    certificateAuthorities:
    - ca_peerOrg1
    adminPrivateKey:
      path: Resource/crypto-config-raft/peerOrganizations/org1.beijinca.com/users/Admin@org1.beijinca.com/msp/keystore/5542aac0ecbfded93112eceb50b46f943407d1ec7787b1fc5d239571720a3d6d_sk
    signedCert:
      path: Resource/crypto-config-raft/peerOrganizations/org1.beijinca.com/users/Admin@org1.beijinca.com/msp/signcerts/Admin@org1.beijinca.com-cert.pem

orderers:
  orderer.beijinca.com:
    url: grpcs://192.168.1.164:7050
    grpcOptions:
      grpc-max-send-message-length: 15
      grpc.keepalive_time_ms: 360000
      grpc.keepalive_timeout_ms: 180000
      hostnameOverride: orderer.beijinca.com
      sslProvider: openSSL
      negotiationType: TLS
    tlsCACerts:
      path: Resource/crypto-config-raft/ordererOrganizations/beijinca.com/orderers/orderer.beijinca.com/tls/ca.crt

peers:
  peer0.org1.beijinca.com:
    url: grpcs://192.168.1.164:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.beijinca.com
      grpc.http2.keepalive_time: 15
      sslProvider: openSSL
      negotiationType: TLS
      hostnameOverride: peer0.org1.beijinca.com
    tlsCACerts:
      path: Resource/crypto-config-raft/peerOrganizations/org1.beijinca.com/peers/peer0.org1.beijinca.com/tls/ca.crt

  peer1.org1.beijinca.com:
    url: grpcs://192.168.1.164:8051
    grpcOptions:
      ssl-target-name-override: peer1.org1.beijinca.com
      grpc.http2.keepalive_time: 15
      sslProvider: openSSL
      hostnameOverride: peer1.org1.beijinca.com
      negotiationType: TLS
    tlsCACerts:
      path: Resource/crypto-config-raft/peerOrganizations/org1.beijinca.com/peers/peer1.org1.beijinca.com/tls/ca.crt

  peer2.org1.beijinca.com:
    url: grpcs://192.168.1.164:9051
    grpcOptions:
      ssl-target-name-override: peer2.org1.beijinca.com
      grpc.http2.keepalive_time: 15
      sslProvider: openSSL
      hostnameOverride: peer2.org1.beijinca.com
      negotiationType: TLS
    tlsCACerts:
      path: Resource/crypto-config-raft/peerOrganizations/org1.beijinca.com/peers/peer2.org1.beijinca.com/tls/ca.crt

certificateAuthorities:
  ca_peerOrg1:
    url: grpcs://192.168.1.164:7054
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca_peerOrg1
    tlsCACerts:
      path: Resource/crypto-config-raft/peerOrganizations/org1.beijinca.com/tlsca/tlsca.org1.beijinca.com-cert.pem

chaincodes:
  crm:
    chaincodeVersion: v1
    chaincodeFilePath: Resource/Chaincode
    chaincodePath: github.com/CRM
    chaincodeName: crm
    chaincodeLanguage: GO
  mycc:
    chaincodeVersion: v1
    chaincodeFilePath: Resource/Chaincode
    chaincodePath: github.com/mycc
    chaincodeName: mycc
    chaincodeLanguage: GO