name: "Network-Config"
x-type: "hlfv1"
version: 1.0.0
description: "The network config"

client:
  # Which organization does this application instance belong to? The value must be the name of an org
  # defined under "organizations"
  organization: Org1

  # Some SDKs support pluggable KV stores, the properties under "credentialStore"
  # are implementation specific
  credentialStore:
    # [Optional]. Specific to FileKeyValueStore.js or similar implementations in other SDKs. Can be others
    # if using an alternative impl. For instance, CouchDBKeyValueStore.js would require an object
    # here for properties like url, db name, etc.
    path: "Org1User"

    # [Optional]. Specific to the CryptoSuite implementation. Software-based implementations like
    # CryptoSuite_ECDSA_AES.js in node SDK requires a key store. PKCS#11 based implementations does
    # not.
    cryptoStore:
      # Specific to the underlying KeyValueStore that backs the crypto key store.
      path: "Org1User"

    # [Optional]. Specific to Composer environment
    wallet: wallet-name

channels:
  mychannel:
    orderers:
    - orderer0.beijinca.com

    peers:
      peer0.org1.beijinca.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org1.beijinca.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer2.org1.beijinca.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    chaincodes:
    - crm:v1

organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.beijinca.com
    - peer1.org1.beijinca.com
    - peer2.org1.beijinca.com
    certificateAuthorities:
    - ca_peerOrg1
    adminPrivateKey:
      path: Resource/Org1User/Admin@org1.beijinca.com/msp/keystore/1890a51bb0f2f19093c3ea1032a8de2abf68305f42dd9ea5002e972edce68110_sk
    signedCert:
      path: Resource/Org1User/Admin@org1.beijinca.com/msp/signcerts/Admin@org1.beijinca.com-cert.pem

orderers:
  orderer0.beijinca.com:
    url: grpc://192.168.1.164:7050
    grpcOptions:
      grpc-max-send-message-length: 15
      grpc.keepalive_time_ms: 360000
      grpc.keepalive_timeout_ms: 180000

  orderer1.beijinca.com:
    url: grpc://192.168.1.164:8050
    grpcOptions:
      grpc-max-send-message-length: 15
      grpc.keepalive_time_ms: 360000
      grpc.keepalive_timeout_ms: 180000

  orderer2.beijinca.com:
    url: grpc://192.168.1.164:9050
    grpcOptions:
      grpc-max-send-message-length: 15
      grpc.keepalive_time_ms: 360000
      grpc.keepalive_timeout_ms: 180000

peers:
  peer0.org1.beijinca.com:
    url: grpc://192.168.1.164:7051
    grpcOptions:
      grpc.http2.keepalive_time: 15

  peer1.org1.beijinca.com:
    url: grpc://192.168.1.164:7056

  peer2.org1.beijinca.com:
    url: grpc://192.168.1.164:7060

certificateAuthorities:
  ca_peerOrg1:
    url: grpc://192.168.1.164:7054
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca_peerOrg1

chaincodes:
  crm:
    chaincodeVersion: v1
    chaincodeFilePath: Resource/Chaincode
    chaincodePath: github.com/CRM
    chaincodeName: crm
    chaincodeLanguage: GO